#!/bin/sh

date=`./maxdate`
cvs ci -m 'release $date'
cvs tag -F rel-$date

echo -n "Repository checked in and tagged (Press RETURN)"
read answert

doc="`ls [A-Z]*`"
impl="`ls *.[ch] |grep -v test`"
examples="`ls examples/*.{c,aig} examples/makefile|sed -e 's,^,examples/,'`"
files="$doc $impl $examples"

dir="/tmp/aiger-$date"
if [ -d $dir ]
then
  echo -n "Will delete '$dir' (Press RETURN)."
  read answer
  rm -rf $dir || exit 1
fi

mkdir $dir || exit 1
for f in $files
do
  cp $f $dir
done
