#!/bin/sh
date=`./maxdate`
cvs ci -m 'release $date'
cvs tag -F rel-$date
files="`ls [A-Z] makefile`"
files="$files `ls *.[ch] |grep -v test`"
files="$files `ls examples/*.{c,h,aig} examples/makefile`"

dir="/tmp/aiger-$date"
if [ -d $dir ]
then
  echo -n "Found '$dir', remove? (yes/no) "
  read answer
  if [ ! X"$answer" = Xyes ]
  then
    echo "*** release: abort"
    exit 1
  fi
fi
