#!/bin/sh

date=`./maxdate`
cvs ci -m 'release $date'
cvs tag -F rel-$date

echo -n "Repository checked in and tagged (Press RETURN)"
read answert

files="`ls [A-Z]* makefile`"
files="$files `ls *.[ch] |grep -v test`"
files="$files `ls examples/*.{c,aig} examples/makefile`"

dir="/tmp/aiger-$date"
if [ -d $dir ]
then
  echo -n "Will delete '$dir' (Press RETURN)."
  read answer
  rm -rf $dir || exit 1
fi

mkdir $dir || exit 1
for f in $files
do
  cp $f $dir
done
