#!/bin/sh
echo "[testaigbmc]";./testaigbmc
echo "[testaigtoaig]";./testaigtoaig
echo "[testsimpaig]";./testsimpaig
echo "[testsmvtoaig]";./testsmvtoaig
echo "[testandtoaig]";./testandtoaig
echo "[testbliftoaig]";./testbliftoaig
