#!/bin/sh
cp $1 /tmp/tmp1.blif
./bliftoaig $1 /tmp/tmp.aig
./aigtoblif /tmp/tmp.aig /tmp/tmp2.blif
vis -x -c 'seq_verify -b /tmp/tmp1.blif /tmp/tmp2.blif'
rm -f /tmp/tmp1.blif /tmp/tmp.aig /tmp/tmp2.blif
